### ISSUE TITLE
Official app?

### ISSUE THREAD

**Issue by scith** [YunoHost-Apps/keeweb_ynh#1]
Make the app official? https://github.com/yunohost/apps#how-to-propose-your-app-to-be-integrated-in-the-official-applications-list

**Comment by scith** [comment]
YEPs: https://github.com/YunoHost/doc/blob/95961f5d3b17967c9777fe0a22e37f081ec58ee9/packaging_apps_guidelines_fr.md

- [ ] YEP 1.8: To do
- [x] YEP 1.10: Sources are synced with upstream
- [ ] YEP 1.11: To do
- [ ] **YEP 2.10**: To do, but how??
- [ ] **YEP 2.18.5**: Not working, why not?
- [ ] YEP 3.4: Is it needed for this app?
- [ ] YEP 3.6: What is this?
- [ ] YEP 4.1: No user management in Keeweb. Is it needed to develop a custom link (with confs for each user), given that users can store the conf in the web browser?
- [ ] YEP 4.2: Same
- [ ] **YEP 4.2.1**: Not sure when the conf is destroyed, as it lives in the user's browser storage...

Looking good so far?

**Comment by maniackcrudelis** [comment]
Nice!

Package linter:                         SUCCESS
Installation:                           SUCCESS
Suppression:                            SUCCESS
Installation en sous-dossier:           SUCCESS
Suppression depuis sous-dossier:        SUCCESS
Installation à la racine:               SUCCESS
Suppression depuis racine:              SUCCESS
Upgrade:                                SUCCESS
Installation privée:                    SUCCESS
Installation publique:                  SUCCESS
Installation multi-instance:            SUCCESS
Mauvais utilisateur:                    Not evaluated.
Erreur de domaine:                      SUCCESS
Correction de path:                     SUCCESS
Port déjà utilisé:                      Not evaluated.
Backup:                                 SUCCESS
Restore:                                SUCCESS
                    Notes de résultats: 21/21 - 20/20 \o/

**Comment by alexAubin** [comment]
Closing because we have no official apps anymore
