### ISSUE TITLE
Garbage html page

### ISSUE THREAD

**Issue by kidonsky** [YunoHost-Apps/keeweb_ynh#25]
### Describe the bug

Installation was ok without any suspect log. But when I open the app I got the pure html (/ js ?) printed.

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.4.1 (stable)
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master

### Steps to reproduce

- Webadmin installation
- See garbage
![keeweb_garbage](https://user-images.githubusercontent.com/12858135/143940779-38f8ce7a-0ed3-4b9c-84ee-6bfc17c23079.png)

Thank you !

**Comment by czen** [comment]
I got the same error on yunohost 4.3.4

**Comment by fragilbert** [comment]
Same error after upgrading to yunohost 4.3.4.1 (stable)

**Comment by moutonjr** [comment]
Hello, same here. Can someone from admin can rollback or patch ?

**Comment by moutonjr** [comment]
Found the issue. By adding YunoHost button layout on top of Keeweb, it's breaking webpage interpretation. ynh_overlay doesn't have its place in a security app anyway.

```
# Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
```

**Comment by ericgaspar** [comment]
closing with #28
