### ISSUE TITLE
Insatallation faildel

### ISSUE THREAD

**Issue by nathanael-h** [YunoHost-Apps/keeweb_ynh#3]
Hello, 
I have yunohost on a debian 8 vps. Keeweb installation failed. 
Wich info do you need to know if the problem is with my server or with keeweb_ynh package ? 
Best regards,
Nath

**Comment by scith** [comment]
Hi, YNH 2.4?
Can you install with `sudo yunohost install https://github.com/YunoHost-Apps/keeweb_ynh --verbose` and let me know if you see anything standing out?
Or with the web interface you can toggle the console view

Thanks

**Comment by nathanael-h** [comment]
I did it via the terminal. And it works ! So where was the problem ? I do not know... 
NB : the command is `sudo yunohost app install ...` ;-) 
Thank's for the quick reply and the y u no host package :+1:
