### ISSUE TITLE
config.json?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/keeweb_ynh#6]
In readme, it's written

> In your config.json add the "files" entry with the appropriate settings

Where can w find the config.json inside a yunohost server?

**Comment by scith** [comment]
Hi, the file is in /var/www/keeweb
Cheers

**Comment by jacen05** [comment]
Hello, just to add that upgrading today from a quite older version failed. 
I found out that was due to a missing config.json file, so by manually creating it I managed to get the app working again. 
Maybe you could add a check for the file in the upgrade script?
