### ISSUE TITLE
how to open local file?

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/keeweb_ynh#7]
Hello,

I have open a local file and I can access it from my computer with Firefox but if I open my keeweb from an other place, my local file is not listed so I can't enter. I have to open a file from computer, dropbox...
So, right now, I can't use keeweb from anywhere, only from my computer.

I was thinking to modify config.json but first, I don't want my local file to be listed to other users of Yunohost, second, I have to fill in 
"files": [{ // pre-defined files that will appear on Open page
    "storage": "webdav", // dropbox, webdav, etc...
    "name": "My file", // file name, as it will be displayed in UI
    "path": "webdav-url", // full path to file, including file name, e.g. WebDAV url
    "options": { "user": "", "password": "" } // only for WebDAV, server auth details
  }],
  "showOnlyFilesFromConfig": false // allow to open only files from config, remove previously opened files
}
and I don't know what to write for storage (local is good?), for path (I couldn't find the url of the local file...).

**Comment by scith** [comment]
Hi, by default Keeweb does not store the files. The files can only be opened from your computer and saved on your computer.

To store the file on the server, you need to use Nextcloud, Owncloud, Dropbox or Google Drive.
In the context of YunoHost, you can install Nextcloud (on the same domain) and then open files from there as explained on the readme.

Cheers

**Comment by Thatoo** [comment]
I see. How is it that from my computer/Firefox it works then? The file is stored in my Firefox?

That could be an improvement then for keeweb Yunohost to allow to store files locally in the user's folder. I'm not planning to install Nextcloud just to store the keeweb file and Yunohost users should not have to open a Dropbox or Google drive.

**Comment by scith** [comment]
Yes the file is stored on Firefox if you do not save it on the computer.
Unfortunately, the app is designed to be used this way (it's called a "browser storage" app). This is what prevents me from suggesting the app to become official. This behavior is not intuitive in the context of YunoHost, as your ticket shows as well...

I don't see a way around it, as I do not maintain the Keeweb app.

**Comment by Thatoo** [comment]
indeed, it's not so yunohost friendly :-)
which is a shame because it has real value for yunohost users.

**Comment by Thatoo** [comment]
I open a new issue on the github of keeweb : https://github.com/keeweb/keeweb/issues/597

**Comment by Thatoo** [comment]
Someone answered and closed my issue but I'm not sure it helps...

**Comment by scith** [comment]
I'll look into it

**Comment by Thatoo** [comment]
I have answered the guy https://github.com/keeweb/keeweb/issues/597
I don't understand why they don't offer that option, to store the file locally....

**Comment by decentral1se** [comment]
Hmmm, strange thread that #597 one ... I've just read https://bondari.com/news/post/host-your-own-multi-user-password-manager-with-keeweb-and-webdav and https://github.com/keeweb/keeweb/wiki/WebDAV-Config. It seems like  would need to extend this package to optionally include a webdav server and update the configuration to know that it is there. This should be optional I suppose. Having to install Nextcloud just to sync a password sounds like overkill to me ...
