### ISSUE TITLE
Fail to install in yunohost

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/keeweb_ynh#8]
Hi there,

Using the web administration interface on a RPi3/DebianJessie, installation of the app in publc mode on its own subdomain (pass.domain.tld)  fails. Error occurs when updating the nginx conf : "Job for nginx.service failed" and then the uninstall script takes over.
Nginx is running fine and I can reload it by hand with "sudo service nginx reload" just as the install script calls.
Any idea ? I have already a keeweb instance in my yunohost, but located on "domain.tld/keeweb". Maybe I should delete this one first ?
Thanks for your attention and your answers, I can provide details as needed.

--
Versions used : 
yunohost    2.6.4
yunohost-admin    2.6.1
moulinette    2.6.1
ssowat    2.6.8

**Comment by Jaxom99** [comment]
Update : installation worked via the command line using the same settings. I got the tip from https://github.com/YunoHost-Apps/keeweb_ynh/issues/3 which I had not read before. And the install indicated no bug or failed step.
So I guess the bug is still in there somewhere...

**Comment by Jaxom99** [comment]
Okay after looking at the right log (nginx/error.log) it mentions this

```
2017/08/09 13:28:58 [emerg] 10808#0: invalid number of arguments in "location" directive in /etc/nginx/conf.d/pass.tchack.xyz.d/keeweb__2.conf:1

2017/08/09 13:28:59 [notice] 10856#0: signal process started

2017/08/09 13:35:05 [emerg] 11737#0: invalid number of arguments in "location" directive in /etc/nginx/conf.d/pass.tchack.xyz.d/keeweb__2.conf:1

2017/08/09 13:35:06 [notice] 11785#0: signal process started

2017/08/09 20:40:03 [emerg] 30828#0: invalid number of arguments in "location" directive in /etc/nginx/conf.d/pass.tchack.xyz.d/keeweb__2.conf:1

2017/08/09 20:40:05 [notice] 30897#0: signal process started
```

Might be helpful...

**Comment by billietl** [comment]
Hi,
I can't install this app either, though I don't see these errors in nginx' logs...

As proposed in #3, here are the install logs : https://framabin.org/?07932bc4cc2efa8d#bgoqN2W34kaVJBl+ttC8PbALFZjowDRR//KFg3AGZoM=
Verison used : 
yunohost: "2.7.2",
yunohost-admin: "2.7.2",
moulinette: "2.7.2",
ssowat: "2.7.2"

Hope it helps...
